### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by grumpi** [leeoniya/domvm#107]
I went through my installed browsers after porting my code to domvm 2.x-dev to check if I see consistent behavior for my app.

Chrome and Firefox appear fine. In Internet Explorer, I used to have to add a Promise polyfill and then it would work (with 1.x-dev). However, not anymore. By means of logging, I was able to track the problem in my code down to the point where I call `vm.redraw()` for the first time. I discovered that it fails silently (i.e. the logging statement after `vm.redraw()` never gets executed).

So, I figured the first thing to do is to run the test suite on my version of Internet Explorer 11 (11.0.9600.18525 / 11.0.37).

I think I'm doing something wrong since pretty much all the tests fail (no matter if I polyfill Promise first or not).

I figured I'd ask first if you know what's going on before delving deeper into debugging Internet Explorer related mysteries. :)

```
Died on test #1    at Anonymous function (http://127.0.0.1:8000/test/tests.js:45:2)
   at Global code (http://127.0.0.1:8000/test/tests.js:37:2): Unable to get property 'createElement' of undefined or null reference@ 3 msSource:  TypeError: Unable to get property 'createElement' of undefined or null reference
   at createElement (http://127.0.0.1:8000/dist/full/domvm.full.js:488:2)
   at hydrate (http://127.0.0.1:8000/dist/full/domvm.full.js:753:4)
   at redrawSync (http://127.0.0.1:8000/dist/full/domvm.full.js:1435:6)
   at mount (http://127.0.0.1:8000/dist/full/domvm.full.js:1334:3)
   at Anonymous function (http://127.0.0.1:8000/test/tests.js:50:3)
   at runTest (http://127.0.0.1:8000/test/qunit-2.0.1.js:726:4)
   at Test.prototype.run (http://127.0.0.1:8000/test/qunit-2.0.1.js:711:4)
   at Anonymous function (http://127.0.0.1:8000/test/qunit-2.0.1.js:874:6)
   at process (http://127.0.0.1:8000/test/qunit-2.0.1.js:550:4)
   at begin (http://127.0.0.1:8000/test/qunit-2.0.1.js:532:2)
 ```

**Comment by yosbelms** [comment]
I filed [this](https://github.com/leeoniya/domvm/issues/85) issue some time ago to avoid things like that. We concluded the discussion with https://github.com/leeoniya/domvm/issues/85#issuecomment-228470385

**Comment by leeoniya** [comment]
heh, the Node vs Browser environment detection code was returning "object" under IE11:

https://github.com/leeoniya/domvm/blob/2.x-dev/src/utils.js#L1

```js
ENV_DOM = typeof HTMLElement == "function";
````

tweaked a couple other tests to account for IE11 differences. works fine now under IE11, IE10. One failure under IE9 due to readOnly attribute getting auto camel-cased by the browser.

should be fixed now.

**Comment by grumpi** [comment]
Thanks. We all know IE is madness, but unfortunately there are still people using it.

**Comment by leeoniya** [comment]
Never forget, **I lived through IE6**

![300x](https://cloud.githubusercontent.com/assets/43234/20838757/8fec9a92-b86f-11e6-855b-ebc00b8ccc81.jpg)

**Comment by grumpi** [comment]
Things are working just fine now in IE11 for me (after fixing the browser inconsistencies I ran into with my own code :grin:).

Behavior is consistent for my app, too (I wasn't really expecting it to be, since I was messing around with input elements that move around - in order to simulate editable content without getting into contenteditable-hell).
